version: '3'

services:
  mysql:
    restart: always
    image: mysql:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
             --default-authentication-plugin=mysql_native_password
             --init-file /docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.envs/.mysql
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - my-mysqlvolume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db-mysql
  php:
    image: yiisoftware/yii2-php:7.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./app:/app:delegated
    ports:
      - '8000:80'
    env_file:
      - ./.envs/.mysql
    depends_on:
      - mysql
    networks:
      - db-mysql
volumes:
  my-mysqlvolume:
networks:
  db-mysql:
    driver: bridge